<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use DB;

class ExerciseSeeder extends Seeder
{
    public function run()
    {
        DB::table('exercises')->truncate();
        DB::table('exercises')->insert([
            [
                'id' => 9,
                'title' => 'Checking in',
                'description' => null,
                'instructions' => null,
                'subtype' => 99,
                'image_name' => null,
                'video_name' => null,
                'extra_info' => null,
                'attempts_number' => null,
                'deleted_at' => null,
                'section_id' => 1,
                'exercise_type_id' => 6,
                'position' => 1,
                'translated_instructions' => null,
            ],
            [
                'id' => 10,
                'title' => 'Checking in',
                'description' => 'Number the steps (1-8) that you will follow to complete this lesson.',
                'instructions' => null,
                'subtype' => 99,
                'image_name' => null,
                'video_name' => null,
                'extra_info' => null,
                'attempts_number' => null,
                'deleted_at' => null,
                'section_id' => 1,
                'exercise_type_id' => 1,
                'position' => 2,
                'translated_instructions' => null,
            ],
            [
                'id' => 16,
                'title' => 'Meet the characters',
                'description' => 'Listen the audio pieces to know the characters',
                'instructions' => null,
                'subtype' => null,
                'image_name' => null,
                'video_name' => null,
                'extra_info' => null,
                'attempts_number' => null,
                'deleted_at' => null,
                'section_id' => 1,
                'exercise_type_id' => 5,
                'position' => 3,
                'translated_instructions' => null,
            ],
            [
                'id' => 12,
                'title' => 'Predicting',
                'description' => null,
                'instructions' => 'The pictures summarize the video. Read the predictions below and choose the letter that best represents what you think will happen.',
                'subtype' => 1,
                'image_name' => 'steven_universe.png',
                'video_name' => 'n1t2.mp4',
                'extra_info' => null,
                'attempts_number' => null,
                'deleted_at' => null,
                'section_id' => 1,
                'exercise_type_id' => 2,
                'position' => 5,
                'translated_instructions' => null,
            ],
            [
                'id' => 13,
                'title' => 'What do you hear?',
                'description' => 'Listen to the audio extract and select the word you hear.',
                'instructions' => null,
                'subtype' => 2,
                'image_name' => 'FdaSPOVrX2KSfHbYpLoDg5bHTjq0p50c152oGIGr.jpg',
                'video_name' => 'n1t2.mp4',
                'extra_info' => null,
                'attempts_number' => null,
                'deleted_at' => null,
                'section_id' => 1,
                'exercise_type_id' => 2,
                'position' => 4,
                'translated_instructions' => null,
            ],
            [
                'id' => 11,
                'title' => 'Vocabulary activation',
                'description' => 'Match the words with their correct definition. Check the previous exercise to understand the context of the words',
                'instructions' => null,
                'subtype' => null,
                'image_name' => null,
                'video_name' => null,
                'extra_info' => null,
                'attempts_number' => null,
                'deleted_at' => null,
                'section_id' => 1,
                'exercise_type_id' => 1,
                'position' => 6,
                'translated_instructions' => null,
            ],
            [
                'id' => 19,
                'title' => 'Vocabulary practice',
                'description' => 'Put the words in the correct sentences',
                'instructions' => null,
                'subtype' => 2,
                'image_name' => null,
                'video_name' => null,
                'extra_info' => null,
                'attempts_number' => null,
                'deleted_at' => null,
                'section_id' => 1,
                'exercise_type_id' => 3,
                'position' => 7,
                'translated_instructions' => null,
            ],
            [
                'id' => 988,
                'title' => 'Checking in',
                'description' => 'Now that you have watched the video. Think about your predictions from exercise',
                'instructions' => null,
                'subtype' => 99,
                'image_name' => null,
                'video_name' => null,
                'extra_info' => null,
                'attempts_number' => null,
                'deleted_at' => null,
                'section_id' => 2,
                'exercise_type_id' => 6,
                'position' => 1,
                'translated_instructions' => null,
            ],
            [
                'id' => 14,
                'title' => 'Evaluating Statement',
                'description' => 'Read each statement carefully. Decide whether the statements are TRUE/FALSE or mark I\'M NOT SURE if you do not know the answer',
                'instructions' => null,
                'subtype' => 3,
                'image_name' => null,
                'video_name' => null,
                'extra_info' => null,
                'attempts_number' => null,
                'deleted_at' => null,
                'section_id' => 2,
                'exercise_type_id' => 2,
                'position' => 2,
                'translated_instructions' => null,
            ],
            [
                'id' => 20,
                'title' => 'Multiple Choice',
                'description' => null,
                'instructions' => null,
                'subtype' => 99,
                'image_name' => null,
                'video_name' => null,
                'extra_info' => null,
                'attempts_number' => null,
                'deleted_at' => null,
                'section_id' => 2,
                'exercise_type_id' => 6,
                'position' => 3,
                'translated_instructions' => null,
            ],
            [
                'id' => 18,
                'title' => 'Dictation cloze',
                'description' => 'Listen to the audio extract and complete the missing words from the text (1 word per space).',
                'instructions' => null,
                'subtype' => 1,
                'image_name' => null,
                'video_name' => null,
                'extra_info' => null,
                'attempts_number' => null,
                'deleted_at' => null,
                'section_id' => 2,
                'exercise_type_id' => 3,
                'position' => 4,
                'translated_instructions' => null,
            ],
            [
                'id' => 15,
                'title' => 'Multiple choice',
                'description' => 'Read the questions and answer',
                'instructions' => null,
                'subtype' => 4,
                'image_name' => null,
                'video_name' => null,
                'extra_info' => null,
                'attempts_number' => null,
                'deleted_at' => null,
                'section_id' => 3,
                'exercise_type_id' => 2,
                'position' => 1,
                'translated_instructions' => null,
            ],
            [
                'id' => 17,
                'title' => 'Personal response',
                'description' => 'Answer the question',
                'instructions' => null,
                'subtype' => 1,
                'image_name' => null,
                'video_name' => null,
                'extra_info' => null,
                'attempts_number' => null,
                'deleted_at' => null,
                'section_id' => 3,
                'exercise_type_id' => 4,
                'position' => 2,
                'translated_instructions' => null,
            ],
            [
                'id' => 21,
                'title' => 'Checking in',
                'description' => null,
                'instructions' => null,
                'subtype' => 99,
                'image_name' => null,
                'video_name' => null,
                'extra_info' => null,
                'attempts_number' => null,
                'deleted_at' => null,
                'section_id' => 3,
                'exercise_type_id' => 6,
                'position' => 3,
                'translated_instructions' => null,
            ],
            [
                'id' => 22,
                'title' => 'Checking in',
                'description' => null,
                'instructions' => null,
                'subtype' => 99,
                'image_name' => null,
                'video_name' => null,
                'extra_info' => null,
                'attempts_number' => null,
                'deleted_at' => null,
                'section_id' => 3,
                'exercise_type_id' => 6,
                'position' => 4,
                'translated_instructions' => null,
            ],
            [
                'id' => 4000,
                'title' => 'Checking in',
                'description' => 'Organize',
                'instructions' => null,
                'subtype' => 99,
                'image_name' => null,
                'video_name' => null,
                'extra_info' => null,
                'attempts_number' => null,
                'deleted_at' => '2025-07-14 15:51:08',
                'section_id' => 1,
                'exercise_type_id' => 6,
                'position' => null,
                'translated_instructions' => null,
            ],
            [
                'id' => 4002,
                'title' => 'Organization',
                'description' => null,
                'instructions' => null,
                'subtype' => 99,
                'image_name' => null,
                'video_name' => null,
                'extra_info' => null,
                'attempts_number' => null,
                'deleted_at' => '2025-07-17 16:01:20',
                'section_id' => 4000,
                'exercise_type_id' => 6,
                'position' => null,
                'translated_instructions' => null,
            ],
            [
                'id' => 4005,
                'title' => 'Note taking',
                'description' => 'Prepare to listen.',
                'instructions' => '<p><strong>Take </strong>notes&nbsp;<strong>online or a piece of paper</strong> and <strong>write down</strong> <strong>KEY</strong> information from the listening text.</p>',
                'subtype' => 99,
                'image_name' => null,
                'video_name' => null,
                'extra_info' => null,
                'attempts_number' => null,
                'deleted_at' => null,
                'section_id' => 4001,
                'exercise_type_id' => 4,
                'position' => null,
                'translated_instructions' => null,
            ],
            [
                'id' => 4003,
                'title' => 'xxxx',
                'description' => 'Meet the characters',
                'instructions' => null,
                'subtype' => 1,
                'image_name' => null,
                'video_name' => null,
                'extra_info' => null,
                'attempts_number' => null,
                'deleted_at' => '2025-07-17 16:43:07',
                'section_id' => 4003,
                'exercise_type_id' => 1,
                'position' => null,
                'translated_instructions' => null,
            ],
            [
                'id' => 4001,
                'title' => 'Organizations',
                'description' => 'hink about what you will need to complete this lesson',
                'instructions' => '<p>Tick <strong>(<strong id="docs-internal-guid-39544017-7fff-dd5c-86a7-8358c4852e27">Ô£ô)</strong></strong><strong>&nbsp;</strong>the steps that you plan to take</p>',
                'subtype' => 99,
                'image_name' => null,
                'video_name' => null,
                'extra_info' => null,
                'attempts_number' => null,
                'deleted_at' => '2025-07-26 18:10:28',
                'section_id' => 4000,
                'exercise_type_id' => 6,
                'position' => null,
                'translated_instructions' => null,
            ],
            [
                'id' => 4019,
                'title' => 'Evaluate strategy',
                'description' => 'Think about the strategies you used during this lesson.',
                'instructions' => null,
                'subtype' => 99,
                'image_name' => null,
                'video_name' => null,
                'extra_info' => null,
                'attempts_number' => null,
                'deleted_at' => null,
                'section_id' => 4002,
                'exercise_type_id' => 6,
                'position' => 3,
                'translated_instructions' => null,
            ],
            [
                'id' => 4014,
                'title' => 'Evaluating statements',
                'description' => null,
                'instructions' => '<p><strong>Read </strong>the statements carefully. <strong>Decide </strong>whether the statements <strong>are </strong>TRUE/FALSE or <strong>mark </strong>I&rsquo;M NOT SURE if you do not know the answer.</p>',
                'subtype' => 3,
                'image_name' => null,
                'video_name' => null,
                'extra_info' => null,
                'attempts_number' => null,
                'deleted_at' => null,
                'section_id' => 4001,
                'exercise_type_id' => 2,
                'position' => null,
                'translated_instructions' => null,
            ],
            [
                'id' => 4017,
                'title' => 'Personal response',
                'description' => 'Think about the conversation Cole had with James.',
                'instructions' => '<p>Cole seems torn about Jame&rsquo;s advice. What <strong>would you recommend</strong> he do? <strong>Choose </strong>the option you think is best for Cole.</p>',
                'subtype' => 1,
                'image_name' => null,
                'video_name' => null,
                'extra_info' => null,
                'attempts_number' => null,
                'deleted_at' => null,
                'section_id' => 4002,
                'exercise_type_id' => 4,
                'position' => 2,
                'translated_instructions' => null,
            ],
            [
                'id' => 4012,
                'title' => 'Resources',
                'description' => 'Think about the resources you have used so far. Focus in the vocabulary.',
                'instructions' => null,
                'subtype' => 991,
                'image_name' => null,
                'video_name' => null,
                'extra_info' => null,
                'attempts_number' => null,
                'deleted_at' => '2025-07-30 05:23:12',
                'section_id' => 4000,
                'exercise_type_id' => 4,
                'position' => null,
                'translated_instructions' => null,
            ],
            [
                'id' => 4004,
                'title' => 'Organization',
                'description' => 'Organize yourself.',
                'instructions' => '<p><strong>Think </strong>about how you <strong>are going to start working</strong> and <strong>complete </strong>this section.</p>',
                'subtype' => 99,
                'image_name' => null,
                'video_name' => null,
                'extra_info' => null,
                'attempts_number' => null,
                'deleted_at' => null,
                'section_id' => 4000,
                'exercise_type_id' => 6,
                'position' => 1,
                'translated_instructions' => null,
            ],
            [
                'id' => 4024,
                'title' => 'What do you hear?',
                'description' => 'Identify sounds.',
                'instructions' => '<p><strong>Listen </strong>to the audio extracts and <strong>select </strong>the words you <strong>hear</strong>.</p>',
                'subtype' => 2,
                'image_name' => null,
                'video_name' => null,
                'extra_info' => null,
                'attempts_number' => null,
                'deleted_at' => null,
                'section_id' => 4003,
                'exercise_type_id' => 2,
                'position' => 3,
                'translated_instructions' => null,
            ],
            [
                'id' => 4011,
                'title' => 'Resources',
                'description' => 'Think about the resources you have used so far.',
                'instructions' => null,
                'subtype' => 99,
                'image_name' => null,
                'video_name' => null,
                'extra_info' => null,
                'attempts_number' => null,
                'deleted_at' => '2025-08-19 19:20:40',
                'section_id' => 4000,
                'exercise_type_id' => 6,
                'position' => 6,
                'translated_instructions' => null,
            ],
            [
                'id' => 4009,
                'title' => 'Activate vocabulary',
                'description' => 'Familiarize yourself with new vocabulary.',
                'instructions' => '<p><strong>Match</strong> the words with their correct definitions. <strong>Check </strong>the <strong>glossary</strong> <strong>to see</strong> an example sentence for each word.</p>',
                'subtype' => 1,
                'image_name' => null,
                'video_name' => null,
                'extra_info' => null,
                'attempts_number' => null,
                'deleted_at' => null,
                'section_id' => 4000,
                'exercise_type_id' => 1,
                'position' => 4,
                'translated_instructions' => null,
            ],
            [
                'id' => 4013,
                'title' => 'Resources',
                'description' => 'Think about the resources you have used so far. Focus on vocabulary.',
                'instructions' => null,
                'subtype' => 99,
                'image_name' => null,
                'video_name' => null,
                'extra_info' => null,
                'attempts_number' => null,
                'deleted_at' => null,
                'section_id' => 4000,
                'exercise_type_id' => 4,
                'position' => 7,
                'translated_instructions' => null,
            ],
            [
                'id' => 4015,
                'title' => 'Monitoring',
                'description' => 'Think about how well you listened.',
                'instructions' => null,
                'subtype' => 99,
                'image_name' => null,
                'video_name' => null,
                'extra_info' => null,
                'attempts_number' => null,
                'deleted_at' => null,
                'section_id' => 4001,
                'exercise_type_id' => 6,
                'position' => null,
                'translated_instructions' => null,
            ],
            [
                'id' => 4018,
                'title' => 'What do you... 2',
                'description' => null,
                'instructions' => null,
                'subtype' => 4,
                'image_name' => null,
                'video_name' => null,
                'extra_info' => null,
                'attempts_number' => null,
                'deleted_at' => '2025-07-30 06:04:20',
                'section_id' => 4002,
                'exercise_type_id' => 2,
                'position' => null,
                'translated_instructions' => null,
            ],
            [
                'id' => 4022,
                'title' => 'Note taking',
                'description' => 'Prepare to listen.',
                'instructions' => '<p><strong>Take </strong>notes&nbsp;<strong>online or a piece of paper</strong>&nbsp;and <strong>write down</strong>&nbsp;<strong>KEY</strong> information from the listening text.</p>',
                'subtype' => 99,
                'image_name' => null,
                'video_name' => null,
                'extra_info' => null,
                'attempts_number' => null,
                'deleted_at' => null,
                'section_id' => 4004,
                'exercise_type_id' => 4,
                'position' => 1,
                'translated_instructions' => null,
            ],
            [
                'id' => 4010,
                'title' => 'Practice your vocabulary',
                'description' => 'In this exercise you will practice the vocabulary from the "activate vocabulary" exercise.',
                'instructions' => '<p><strong>Complete </strong>the words from the box in the correct sentences. <strong>Don\'t use</strong>&nbsp;capital letters, and <strong>be careful </strong>of extra spaces at the beginning or at the end of each word.</p>',
                'subtype' => 2,
                'image_name' => null,
                'video_name' => null,
                'extra_info' => null,
                'attempts_number' => null,
                'deleted_at' => null,
                'section_id' => 4000,
                'exercise_type_id' => 3,
                'position' => 5,
                'translated_instructions' => null,
            ],
            [
                'id' => 4008,
                'title' => 'What do you hear?',
                'description' => 'Identify sounds.',
                'instructions' => '<p><strong>Listen </strong>to the audio extracts and <strong>select </strong>the words you <strong>hear</strong>.</p>',
                'subtype' => 2,
                'image_name' => null,
                'video_name' => null,
                'extra_info' => null,
                'attempts_number' => null,
                'deleted_at' => null,
                'section_id' => 4000,
                'exercise_type_id' => 2,
                'position' => 3,
                'translated_instructions' => null,
            ],
            [
                'id' => 4006,
                'title' => 'What do you think?',
                'description' => 'Watch the video of Cole talking with his mentor, James, and answer the questions below.',
                'instructions' => '<p><strong>Watch </strong><a href="https://drive.google.com/file/d/1UERDB_Gk9FMDyM6Gc4w9U7D-mmcjyVUj/view" target="_blank" rel="noopener">the following video</a> and <strong>answer </strong>the questions.<br><br><br></p>',
                'subtype' => 4,
                'image_name' => null,
                'video_name' => null,
                'extra_info' => null,
                'attempts_number' => null,
                'deleted_at' => null,
                'section_id' => 4002,
                'exercise_type_id' => 2,
                'position' => 1,
                'translated_instructions' => null,
            ],
            [
                'id' => 4025,
                'title' => 'Activate vocabulary',
                'description' => 'Familiarize yourself with new vocabulary.',
                'instructions' => '<p><strong>Match</strong>&nbsp;the words with their correct definitions. <strong>Check </strong>the&nbsp;<strong>glossary</strong> <strong>to see </strong>an example sentence for each word.</p>',
                'subtype' => 1,
                'image_name' => null,
                'video_name' => null,
                'extra_info' => null,
                'attempts_number' => null,
                'deleted_at' => null,
                'section_id' => 4003,
                'exercise_type_id' => 1,
                'position' => 4,
                'translated_instructions' => null,
            ],
            [
                'id' => 4028,
                'title' => 'Resources',
                'description' => 'Think about the resources you have used so far. Focus on vocabulary.',
                'instructions' => null,
                'subtype' => 99,
                'image_name' => null,
                'video_name' => null,
                'extra_info' => null,
                'attempts_number' => null,
                'deleted_at' => null,
                'section_id' => 4003,
                'exercise_type_id' => 4,
                'position' => 7,
                'translated_instructions' => null,
            ],
            [
                'id' => 4027,
                'title' => 'Resources',
                'description' => 'Think about the resources you have used so far.',
                'instructions' => null,
                'subtype' => 99,
                'image_name' => null,
                'video_name' => null,
                'extra_info' => null,
                'attempts_number' => null,
                'deleted_at' => null,
                'section_id' => 4003,
                'exercise_type_id' => 2,
                'position' => 6,
                'translated_instructions' => null,
            ],
            [
                'id' => 4023,
                'title' => 'What do you think?',
                'description' => 'Watch the video of Mr. Holland, a music teacher, explaining why he uses specific music genres in his teaching.',
                'instructions' => '<p dir="ltr"><strong>Watch</strong> the <a href="https://drive.google.com/file/d/1hcH-GE1nMzZSUZVp8y0-aVmxpfLWXde0/view?usp=sharing" target="_blank" rel="noopener">following video</a> and<strong> answer</strong> the questions.</p>\\r\\n<p>&nbsp;</p>\\r\\n<p>&nbsp;</p>',
                'subtype' => 4,
                'image_name' => null,
                'video_name' => null,
                'extra_info' => null,
                'attempts_number' => null,
                'deleted_at' => null,
                'section_id' => 4005,
                'exercise_type_id' => 2,
                'position' => 1,
                'translated_instructions' => null,
            ],
            [
                'id' => 4112,
                'title' => 'Cooperating',
                'description' => null,
                'instructions' => null,
                'subtype' => 99,
                'image_name' => null,
                'video_name' => null,
                'extra_info' => null,
                'attempts_number' => null,
                'deleted_at' => '2025-10-01 10:32:08',
                'section_id' => 4017,
                'exercise_type_id' => 6,
                'position' => null,
                'translated_instructions' => null,
            ],
            [
                'id' => 4042,
                'title' => 'Organization',
                'description' => 'Think about how you are going to start working, and complete this section.',
                'instructions' => null,
                'subtype' => 99,
                'image_name' => null,
                'video_name' => null,
                'extra_info' => null,
                'attempts_number' => null,
                'deleted_at' => null,
                'section_id' => 4006,
                'exercise_type_id' => 4,
                'position' => 1,
                'translated_instructions' => null,
            ],
            [
                'id' => 4021,
                'title' => 'Meet the characters!',
                'description' => 'Listen to Mr. Holland and Miss Lang.',
                'instructions' => '<p><strong>Listen</strong> to the main characters and<strong> familiarize yourself</strong> with their voices. <strong>Do you understand</strong> what they are saying?</p>',
                'subtype' => 1,
                'image_name' => null,
                'video_name' => null,
                'extra_info' => null,
                'attempts_number' => null,
                'deleted_at' => null,
                'section_id' => 4003,
                'exercise_type_id' => 5,
                'position' => 2,
                'translated_instructions' => null,
            ],
            [
                'id' => 4020,
                'title' => 'Organization',
                'description' => 'Think about how you are going to start working, and complete this section.',
                'instructions' => null,
                'subtype' => 99,
                'image_name' => null,
                'video_name' => null,
                'extra_info' => null,
                'attempts_number' => null,
                'deleted_at' => null,
                'section_id' => 4003,
                'exercise_type_id' => 6,
                'position' => 1,
                'translated_instructions' => null,
            ],
            [
                'id' => 4043,
                'title' => 'Organization',
                'description' => 'Think about your goals for this lesson.',
                'instructions' => null,
                'subtype' => 99,
                'image_name' => null,
                'video_name' => null,
                'extra_info' => null,
                'attempts_number' => null,
                'deleted_at' => null,
                'section_id' => 4006,
                'exercise_type_id' => 6,
                'position' => 2,
                'translated_instructions' => null,
            ],
            [
                'id' => 4053,
                'title' => 'Evaluate strategy',
                'description' => 'Think about the resources and strategies you used during this lesson.',
                'instructions' => null,
                'subtype' => 99,
                'image_name' => null,
                'video_name' => null,
                'extra_info' => null,
                'attempts_number' => null,
                'deleted_at' => null,
                'section_id' => 4008,
                'exercise_type_id' => 6,
                'position' => 3,
                'translated_instructions' => null,
            ],
            [
                'id' => 4035,
                'title' => 'Summarize',
                'description' => 'Prepare to listen',
                'instructions' => null,
                'subtype' => 99,
                'image_name' => null,
                'video_name' => null,
                'extra_info' => null,
                'attempts_number' => null,
                'deleted_at' => null,
                'section_id' => 4007,
                'exercise_type_id' => 4,
                'position' => null,
                'translated_instructions' => null,
            ],
            [
                'id' => 4046,
                'title' => 'Activate vocabulary',
                'description' => 'Familiarize yourself with new vocabulary.',
                'instructions' => '<p><strong>Match</strong> the words with their correct definitions. <strong>Check </strong>the <strong>glossary</strong> to see an example sentence for each word.</p>',
                'subtype' => 1,
                'image_name' => null,
                'video_name' => null,
                'extra_info' => null,
                'attempts_number' => null,
                'deleted_at' => null,
                'section_id' => 4006,
                'exercise_type_id' => 1,
                'position' => 5,
                'translated_instructions' => null,
            ],
            [
                'id' => 4037,
                'title' => 'Organization',
                'description' => 'Think about...',
                'instructions' => null,
                'subtype' => 991,
                'image_name' => null,
                'video_name' => null,
                'extra_info' => null,
                'attempts_number' => null,
                'deleted_at' => '2025-08-13 18:20:50',
                'section_id' => 4006,
                'exercise_type_id' => 4,
                'position' => null,
                'translated_instructions' => null,
            ],
            [
                'id' => 4038,
                'title' => 'LLL',
                'description' => null,
                'instructions' => null,
                'subtype' => 99,
                'image_name' => null,
                'video_name' => null,
                'extra_info' => null,
                'attempts_number' => null,
                'deleted_at' => '2025-08-13 18:21:22',
                'section_id' => 4006,
                'exercise_type_id' => 1,
                'position' => null,
                'translated_instructions' => null,
            ],
            [
                'id' => 4039,
                'title' => 'Organization',
                'description' => 'Think about how you are going to start working, and complete this section.',
                'instructions' => null,
                'subtype' => 99,
                'image_name' => null,
                'video_name' => null,
                'extra_info' => null,
                'attempts_number' => null,
                'deleted_at' => '2025-08-15 08:35:10',
                'section_id' => 4006,
                'exercise_type_id' => 6,
                'position' => null,
                'translated_instructions' => null,
            ],
            [
                'id' => 4041,
                'title' => 'Organization',
                'description' => 'Think about how you are going to start working, and complete this section.',
                'instructions' => null,
                'subtype' => 99,
                'image_name' => null,
                'video_name' => null,
                'extra_info' => null,
                'attempts_number' => null,
                'deleted_at' => '2025-08-15 08:35:45',
                'section_id' => 4006,
                'exercise_type_id' => 6,
                'position' => null,
                'translated_instructions' => null,
            ],
            [
                'id' => 4040,
                'title' => 'Organization',
                'description' => 'Think about how you are going to start working, and complete this section.',
                'instructions' => null,
                'subtype' => 99,
                'image_name' => null,
                'video_name' => null,
                'extra_info' => null,
                'attempts_number' => null,
                'deleted_at' => '2025-08-15 08:35:49',
                'section_id' => 4006,
                'exercise_type_id' => 6,
                'position' => null,
                'translated_instructions' => null,
            ],
            [
                'id' => 4034,
                'title' => 'Organization',
                'description' => 'Think about how you are going to start working, and complete this section.',
                'instructions' => '<p>Number the steps (1-8) that you will follow to complete this lesson.</p>',
                'subtype' => 99,
                'image_name' => null,
                'video_name' => null,
                'extra_info' => null,
                'attempts_number' => null,
                'deleted_at' => '2025-08-15 08:41:19',
                'section_id' => 4006,
                'exercise_type_id' => 1,
                'position' => null,
                'translated_instructions' => null,
            ],
            [
                'id' => 4055,
                'title' => 'Organization',
                'description' => 'Think about how you are going to start working, and complete this section.',
                'instructions' => null,
                'subtype' => 99,
                'image_name' => null,
                'video_name' => null,
                'extra_info' => null,
                'attempts_number' => null,
                'deleted_at' => null,
                'section_id' => 4009,
                'exercise_type_id' => 4,
                'position' => 1,
                'translated_instructions' => null,
            ],
            [
                'id' => 4033,
                'title' => 'Evaluate strategy',
                'description' => 'Think about the strategies you used during this lesson.',
                'instructions' => null,
                'subtype' => 99,
                'image_name' => null,
                'video_name' => null,
                'extra_info' => null,
                'attempts_number' => null,
                'deleted_at' => null,
                'section_id' => 4005,
                'exercise_type_id' => 6,
                'position' => 3,
                'translated_instructions' => null,
            ],
            [
                'id' => 4048,
                'title' => 'Checking understanding',
                'description' => null,
                'instructions' => '<p><strong>Watch </strong>the video and <strong>answer </strong>the following questions:</p>',
                'subtype' => 3,
                'image_name' => null,
                'video_name' => null,
                'extra_info' => null,
                'attempts_number' => null,
                'deleted_at' => null,
                'section_id' => 4007,
                'exercise_type_id' => 2,
                'position' => null,
                'translated_instructions' => null,
            ],
            [
                'id' => 4030,
                'title' => 'Monitoring',
                'description' => 'Think about how well you listened.',
                'instructions' => null,
                'subtype' => 99,
                'image_name' => null,
                'video_name' => null,
                'extra_info' => null,
                'attempts_number' => null,
                'deleted_at' => null,
                'section_id' => 4004,
                'exercise_type_id' => 6,
                'position' => 3,
                'translated_instructions' => null,
            ],
            [
                'id' => 4045,
                'title' => 'Predicting',
                'description' => 'Think about what you think is going to happen in the scene you are going to watch.',
                'instructions' => null,
                'subtype' => 1,
                'image_name' => null,
                'video_name' => null,
                'extra_info' => null,
                'attempts_number' => null,
                'deleted_at' => '2025-09-05 00:57:13',
                'section_id' => 4006,
                'exercise_type_id' => 2,
                'position' => 4,
                'translated_instructions' => null,
            ],
            [
                'id' => 4049,
                'title' => 'Resources',
                'description' => 'Think about the strategies you used.',
                'instructions' => null,
                'subtype' => 99,
                'image_name' => null,
                'video_name' => null,
                'extra_info' => null,
                'attempts_number' => null,
                'deleted_at' => null,
                'section_id' => 4007,
                'exercise_type_id' => 4,
                'position' => null,
                'translated_instructions' => null,
            ],
            [
                'id' => 4050,
                'title' => 'Monitoring',
                'description' => 'Think about how well you listened.',
                'instructions' => null,
                'subtype' => 99,
                'image_name' => null,
                'video_name' => null,
                'extra_info' => null,
                'attempts_number' => null,
                'deleted_at' => null,
                'section_id' => 4007,
                'exercise_type_id' => 6,
                'position' => null,
                'translated_instructions' => null,
            ],
            [
                'id' => 4036,
                'title' => 'What do you think?',
                'description' => 'Watch the video of Keith talking to Sebastian and answer the questions below.',
                'instructions' => '<p><strong>Watch </strong>the <a href="https://drive.google.com/file/d/1UWLJJ-TYj2GUWcBgxZUg7TGvc7vQzWdW/view?usp=sharing"><strong>following video</strong></a> and <strong>answer </strong>the questions.</p>\\r\\n<p>&nbsp;</p>\\r\\n<p>&nbsp;</p>',
                'subtype' => 4,
                'image_name' => null,
                'video_name' => null,
                'extra_info' => null,
                'attempts_number' => null,
                'deleted_at' => null,
                'section_id' => 4008,
                'exercise_type_id' => 2,
                'position' => 1,
                'translated_instructions' => null,
            ],
            [
                'id' => 4029,
                'title' => 'Evaluating statements',
                'description' => 'Listen and answer.',
                'instructions' => '<p><strong>Read </strong>the statements carefully. <strong>Decide </strong>whether the statements <strong>are</strong> true/false&nbsp;or <strong>mark </strong>i\'m not sure<strong> </strong>if you do not know the answer.&nbsp;</p>',
                'subtype' => 3,
                'image_name' => null,
                'video_name' => null,
                'extra_info' => null,
                'attempts_number' => null,
                'deleted_at' => null,
                'section_id' => 4004,
                'exercise_type_id' => 2,
                'position' => 2,
                'translated_instructions' => null,
            ],
            [
                'id' => 4054,
                'title' => 'Resources',
                'description' => 'Think of the resources you have used so far.',
                'instructions' => null,
                'subtype' => 99,
                'image_name' => null,
                'video_name' => null,
                'extra_info' => null,
                'attempts_number' => null,
                'deleted_at' => null,
                'section_id' => 4000,
                'exercise_type_id' => 2,
                'position' => 6,
                'translated_instructions' => null,
            ],
            [
                'id' => 4058,
                'title' => 'Summarize',
                'description' => 'Prepare to listen.',
                'instructions' => null,
                'subtype' => 99,
                'image_name' => null,
                'video_name' => null,
                'extra_info' => null,
                'attempts_number' => null,
                'deleted_at' => null,
                'section_id' => 4010,
                'exercise_type_id' => 4,
                'position' => null,
                'translated_instructions' => null,
            ],
            [
                'id' => 4059,
                'title' => 'What do you thinik?',
                'description' => 'Think about the ideas and emotions present in the scene with the Smallbone family.',
                'instructions' => '<p><strong>Read</strong> each statement (1-3) and <strong>choose</strong> the option that best shows your opinion. There are <strong>no</strong> incorrect answers. Think about what <em>you</em> believe.</p>',
                'subtype' => 4,
                'image_name' => null,
                'video_name' => null,
                'extra_info' => null,
                'attempts_number' => null,
                'deleted_at' => null,
                'section_id' => 4011,
                'exercise_type_id' => 2,
                'position' => null,
                'translated_instructions' => null,
            ],
            [
                'id' => 4052,
                'title' => 'Personal response',
                'description' => 'Think about what Keith said to Sebastian.',
                'instructions' => '<p><strong>Imagine </strong>you are Sebastian&rsquo;s friend and you know that Sebastian wants to prevent jazz from dying by opening his own club. What do you <strong>think </strong>about his idea? What <strong>would you do </strong>as his friend? <strong>Choose</strong> the option that best represents what you think.</p>',
                'subtype' => 1,
                'image_name' => null,
                'video_name' => null,
                'extra_info' => null,
                'attempts_number' => null,
                'deleted_at' => null,
                'section_id' => 4008,
                'exercise_type_id' => 4,
                'position' => 2,
                'translated_instructions' => null,
            ],
            [
                'id' => 4044,
                'title' => 'Meet the characters!',
                'description' => 'Listen to Mia and Sebastian.',
                'instructions' => '<p><strong>Listen</strong> to the main characters and <strong>familiarize yourself</strong> with their voices. <strong>Do you understand</strong> what they are saying?</p>',
                'subtype' => 1,
                'image_name' => null,
                'video_name' => null,
                'extra_info' => null,
                'attempts_number' => null,
                'deleted_at' => null,
                'section_id' => 4006,
                'exercise_type_id' => 5,
                'position' => 3,
                'translated_instructions' => null,
            ],
            [
                'id' => 4051,
                'title' => 'Dictation cloze',
                'description' => 'Listen and complete.',
                'instructions' => '<p>In this audio <strong>you will hear </strong>Keith, the lead singer of a Jazz band, talking to Sebastian about Sebastian&rsquo;s view of Jazz. <strong>Listen </strong>to the audio extract and <strong>complete </strong>the missing words (1 word per blank gap).</p>\\r\\n<p><strong>Don\'t use </strong>capital letters, and <strong>be careful </strong>of extra spaces at the beginning or at the end of each word.</p>',
                'subtype' => 1,
                'image_name' => null,
                'video_name' => null,
                'extra_info' => null,
                'attempts_number' => null,
                'deleted_at' => null,
                'section_id' => 4007,
                'exercise_type_id' => 3,
                'position' => null,
                'translated_instructions' => null,
            ],
            [
                'id' => 4007,
                'title' => 'Meet the characters!',
                'description' => 'Listen to Cole and Sophie.',
                'instructions' => '<p><strong>Listen</strong> to the main characters and <strong>familiarize yourself</strong> with their voices. Do you <strong>understand </strong>what <strong>they are saying</strong>?</p>',
                'subtype' => 1,
                'image_name' => null,
                'video_name' => null,
                'extra_info' => null,
                'attempts_number' => null,
                'deleted_at' => null,
                'section_id' => 4000,
                'exercise_type_id' => 5,
                'position' => 2,
                'translated_instructions' => null,
            ],
            [
                'id' => 4032,
                'title' => 'Personal Response',
                'description' => 'Think about the meeting Mr. Holland had.',
                'instructions' => '<p><strong>Imagine </strong>you are a parent attending the<strong> school meeting</strong> and <strong>you were presented </strong>with the arguments of Mr. Holland and the argument of&nbsp; Vice Principal Wolters.&nbsp; <strong>Choose </strong>the option you <strong>agree </strong>with and <strong>explain</strong>.</p>',
                'subtype' => 1,
                'image_name' => null,
                'video_name' => null,
                'extra_info' => null,
                'attempts_number' => null,
                'deleted_at' => null,
                'section_id' => 4005,
                'exercise_type_id' => 4,
                'position' => 2,
                'translated_instructions' => null,
            ],
            [
                'id' => 4031,
                'title' => 'Dictation cloze',
                'description' => 'Listen and complete.',
                'instructions' => '<p dir="ltr">In this audio <strong>you will hear </strong>Mr. Holland trying to console Miss Lang and complete the missing words you hear. <strong>Listen </strong>to the audio extract and <strong>complete </strong>the missing words (1 word per blank gap).</p>\\r\\n<p dir="ltr"><strong>Don\'t </strong>use capital letters, and&nbsp;<strong>be careful&nbsp;</strong>of extra spaces at the beginning or at the end of each word.</p>',
                'subtype' => 1,
                'image_name' => null,
                'video_name' => null,
                'extra_info' => null,
                'attempts_number' => null,
                'deleted_at' => null,
                'section_id' => 4004,
                'exercise_type_id' => 3,
                'position' => 4,
                'translated_instructions' => null,
            ],
            [
                'id' => 4056,
                'title' => 'Meet the characters!',
                'description' => 'Listen to the Smallbone family and to Mr. DeGarmo.',
                'instructions' => '<p><strong>Listen</strong> to the main characters and<strong> familiarize yourself</strong> with their voices. Do you understand what they are saying?</p>',
                'subtype' => 1,
                'image_name' => null,
                'video_name' => null,
                'extra_info' => null,
                'attempts_number' => null,
                'deleted_at' => null,
                'section_id' => 4009,
                'exercise_type_id' => 5,
                'position' => 2,
                'translated_instructions' => null,
            ],
            [
                'id' => 4113,
                'title' => 'Cooperating',
                'description' => null,
                'instructions' => null,
                'subtype' => 99,
                'image_name' => null,
                'video_name' => null,
                'extra_info' => null,
                'attempts_number' => null,
                'deleted_at' => null,
                'section_id' => 4017,
                'exercise_type_id' => 4,
                'position' => 5,
                'translated_instructions' => null,
            ],
            [
                'id' => 4060,
                'title' => 'Predicting',
                'description' => 'Think about what you think is going to happen in the scene you are going to watch.',
                'instructions' => '<p>The pictures summarize the video.</p>',
                'subtype' => 1,
                'image_name' => null,
                'video_name' => null,
                'extra_info' => null,
                'attempts_number' => null,
                'deleted_at' => '2025-08-20 00:53:21',
                'section_id' => 4006,
                'exercise_type_id' => 2,
                'position' => null,
                'translated_instructions' => null,
            ],
            [
                'id' => 4062,
                'title' => 'Practice your vocabulary',
                'description' => 'In this exercise you will practice the vocabulary from the "activate vocabulary" exercise.',
                'instructions' => '<p><strong>Complete</strong> the words from the box in the correct sentences.</p>\\r\\n<p><strong>Don\'t&nbsp;</strong>use capital letters, and&nbsp;<strong>be careful&nbsp;</strong>of extra spaces at the beginning or at the end of each word.</p>',
                'subtype' => 1,
                'image_name' => null,
                'video_name' => null,
                'extra_info' => null,
                'attempts_number' => null,
                'deleted_at' => '2025-08-20 01:05:54',
                'section_id' => 4009,
                'exercise_type_id' => 3,
                'position' => null,
                'translated_instructions' => null,
            ],
            [
                'id' => 4064,
                'title' => 'Checking understanding',
                'description' => null,
                'instructions' => '<p><strong>Watch</strong> the video and <strong>answer</strong> the following questions:</p>',
                'subtype' => 4,
                'image_name' => null,
                'video_name' => null,
                'extra_info' => null,
                'attempts_number' => null,
                'deleted_at' => null,
                'section_id' => 4010,
                'exercise_type_id' => 2,
                'position' => null,
                'translated_instructions' => null,
            ],
            [
                'id' => 4065,
                'title' => 'Resources',
                'description' => 'Think about the strategies you used.',
                'instructions' => null,
                'subtype' => 99,
                'image_name' => null,
                'video_name' => null,
                'extra_info' => null,
                'attempts_number' => null,
                'deleted_at' => null,
                'section_id' => 4010,
                'exercise_type_id' => 4,
                'position' => null,
                'translated_instructions' => null,
            ],
            [
                'id' => 4066,
                'title' => 'Monitoring',
                'description' => 'Think about what was difficult from the video.',
                'instructions' => null,
                'subtype' => 991,
                'image_name' => null,
                'video_name' => null,
                'extra_info' => null,
                'attempts_number' => null,
                'deleted_at' => null,
                'section_id' => 4010,
                'exercise_type_id' => 4,
                'position' => null,
                'translated_instructions' => null,
            ],
            [
                'id' => 4067,
                'title' => 'Dictation cloze',
                'description' => 'Listen and complete.',
                'instructions' => '<p>In this audio you will hear a conversation between David and Helen talking about moving to Nashville.<strong id="docs-internal-guid-2f0d5317-7fff-0edd-a7cb-df7e2da9eacc"> </strong><strong>Listen</strong> to the audio extract and <strong>complete</strong> the missing words (1 word per blank gap).</p>\\r\\n<p><strong>Don\'t&nbsp;</strong>use capital letters, and&nbsp;<strong>be careful&nbsp;</strong>of extra spaces at the beginning or at the end of each word.</p>',
                'subtype' => 1,
                'image_name' => null,
                'video_name' => null,
                'extra_info' => null,
                'attempts_number' => null,
                'deleted_at' => null,
                'section_id' => 4010,
                'exercise_type_id' => 3,
                'position' => null,
                'translated_instructions' => null,
            ],
            [
                'id' => 4068,
                'title' => 'Personal response',
                'description' => 'Think about the characters from the scene you watched.',
                'instructions' => '<p dir="ltr">Choose one character from the video (David, Rebecca, Helen). Imagine you are that person. How do they feel after the heated conversation they had? What are they thinking?</p>\\r\\n<p>&nbsp;</p>',
                'subtype' => 1,
                'image_name' => null,
                'video_name' => null,
                'extra_info' => null,
                'attempts_number' => null,
                'deleted_at' => null,
                'section_id' => 4011,
                'exercise_type_id' => 4,
                'position' => null,
                'translated_instructions' => null,
            ],
            [
                'id' => 4069,
                'title' => 'Personal elaboration',
                'description' => 'Think about what you learned during this lesson.',
                'instructions' => '<p>What have you learned <strong>about music </strong>that can be transferred to a life-long lesson?</p>',
                'subtype' => 99,
                'image_name' => null,
                'video_name' => null,
                'extra_info' => null,
                'attempts_number' => null,
                'deleted_at' => null,
                'section_id' => 4011,
                'exercise_type_id' => 4,
                'position' => null,
                'translated_instructions' => null,
            ],
            [
                'id' => 4070,
                'title' => 'Evaluate strategy',
                'description' => 'Think about the resources and strategies you used during this lesson.',
                'instructions' => null,
                'subtype' => 99,
                'image_name' => null,
                'video_name' => null,
                'extra_info' => null,
                'attempts_number' => null,
                'deleted_at' => null,
                'section_id' => 4011,
                'exercise_type_id' => 6,
                'position' => null,
                'translated_instructions' => null,
            ],
            [
                'id' => 4026,
                'title' => 'Practice your vocabulary',
                'description' => 'In this exercise you will practice the vocabulary from the "activate vocabulary" exercise.',
                'instructions' => '<p><strong>Complete </strong>the words from the box in the correct sentences.</p>\\r\\n<p><strong>Don\'t use </strong>capital letters, and&nbsp;<strong>be careful&nbsp;</strong>of extra spaces at the beginning or at the end of each word.</p>',
                'subtype' => 2,
                'image_name' => null,
                'video_name' => null,
                'extra_info' => null,
                'attempts_number' => null,
                'deleted_at' => null,
                'section_id' => 4003,
                'exercise_type_id' => 3,
                'position' => 5,
                'translated_instructions' => null,
            ],
            [
                'id' => 4057,
                'title' => 'Predicting',
                'description' => 'Think about what you think is going to happen in the scene you are going to watch.',
                'instructions' => '<p>The pictures summarize the video.</p>',
                'subtype' => 1,
                'image_name' => null,
                'video_name' => null,
                'extra_info' => null,
                'attempts_number' => null,
                'deleted_at' => '2025-09-10 09:53:31',
                'section_id' => 4009,
                'exercise_type_id' => 2,
                'position' => null,
                'translated_instructions' => null,
            ],
            [
                'id' => 4078,
                'title' => 'Summarizing',
                'description' => 'Prepare yourself to listen: Take notes online or on a piece of paper and write down KEY information from the listening text.',
                'instructions' => null,
                'subtype' => 99,
                'image_name' => null,
                'video_name' => null,
                'extra_info' => 'Write a short summary (5–6 sentences) that explains the main ideas clearly.  Include important supporting details or examples. Use linking words (e.g., however, for example, finally) to connect ideas.',
                'attempts_number' => null,
                'deleted_at' => '2025-08-26 12:43:52',
                'section_id' => 4013,
                'exercise_type_id' => 4,
                'position' => null,
                'translated_instructions' => null,
            ],
            [
                'id' => 4016,
                'title' => 'Dictation cloze',
                'description' => 'Listen and complete.',
                'instructions' => '<p>In this audio, you <strong>will hear</strong> Cole talking to his mentor, James, about his track. James gives Cole his opinion on it. <strong>Listen </strong>to the audio extract and <strong>complete </strong>the missing words (one word per blank space).</p>\\r\\n<p><strong>Don\'t use</strong> capital letters, and <strong>be careful </strong>of extra spaces at the beginning or at the end of each word.</p>',
                'subtype' => 1,
                'image_name' => null,
                'video_name' => null,
                'extra_info' => null,
                'attempts_number' => null,
                'deleted_at' => null,
                'section_id' => 4001,
                'exercise_type_id' => 3,
                'position' => null,
                'translated_instructions' => null,
            ],
            [
                'id' => 4061,
                'title' => 'Activate vocabulary',
                'description' => 'Familiarize yourself with new vocabulary.',
                'instructions' => '<p><strong>Match</strong>&nbsp;the words with their correct definitions. Check the&nbsp;<strong>glossary</strong> to see an example sentence for each word.</p>',
                'subtype' => 1,
                'image_name' => null,
                'video_name' => null,
                'extra_info' => null,
                'attempts_number' => null,
                'deleted_at' => null,
                'section_id' => 4009,
                'exercise_type_id' => 1,
                'position' => 4,
                'translated_instructions' => null,
            ],
            [
                'id' => 4073,
                'title' => 'Meet the characters!',
                'description' => 'Listen to Alex Fletcher, Cora, Ray and Chris Riley.',
                'instructions' => '<p><strong>Listen </strong>to the main characters and <strong>familiarize </strong>yourself with their voices. <strong>Do you understand </strong>what they are saying?</p>',
                'subtype' => 1,
                'image_name' => null,
                'video_name' => null,
                'extra_info' => null,
                'attempts_number' => null,
                'deleted_at' => null,
                'section_id' => 4012,
                'exercise_type_id' => 5,
                'position' => 2,
                'translated_instructions' => null,
            ],
            [
                'id' => 4074,
                'title' => 'Predicting',
                'description' => 'Read each statement carefully. Do you AGREE or DISAGREE?',
                'instructions' => null,
                'subtype' => 1,
                'image_name' => null,
                'video_name' => null,
                'extra_info' => null,
                'attempts_number' => null,
                'deleted_at' => null,
                'section_id' => 4012,
                'exercise_type_id' => 2,
                'position' => 3,
                'translated_instructions' => null,
            ],
            [
                'id' => 4075,
                'title' => 'Vocabulary activation',
                'description' => 'Familiarize yourself with new vocabulary.',
                'instructions' => '<p><strong>Match </strong>the words with their correct definitions. <strong>Check</strong> the <strong>glossary to see</strong> an example sentence for each word.&nbsp;</p>',
                'subtype' => 1,
                'image_name' => null,
                'video_name' => null,
                'extra_info' => null,
                'attempts_number' => null,
                'deleted_at' => null,
                'section_id' => 4012,
                'exercise_type_id' => 1,
                'position' => 4,
                'translated_instructions' => null,
            ],
            [
                'id' => 4077,
                'title' => 'Organization',
                'description' => 'Think about different listening strategies.',
                'instructions' => null,
                'subtype' => 99,
                'image_name' => null,
                'video_name' => null,
                'extra_info' => null,
                'attempts_number' => null,
                'deleted_at' => null,
                'section_id' => 4012,
                'exercise_type_id' => 6,
                'position' => 6,
                'translated_instructions' => null,
            ],
            [
                'id' => 4081,
                'title' => 'Monitoring',
                'description' => 'Think about the challenges you faced during this listening activity',
                'instructions' => null,
                'subtype' => 991,
                'image_name' => null,
                'video_name' => null,
                'extra_info' => null,
                'attempts_number' => null,
                'deleted_at' => null,
                'section_id' => 4013,
                'exercise_type_id' => 4,
                'position' => 3,
                'translated_instructions' => null,
            ],
            [
                'id' => 4076,
                'title' => 'Vocabulary practice',
                'description' => 'In this exercise you will practice the vocabulary from the "activate vocabulary" exercise.',
                'instructions' => '<p><strong>Complete&nbsp;</strong>the words from the box in the correct sentences.&nbsp;<strong>Don\'t use</strong>&nbsp;capital letters, and&nbsp;<strong>be careful&nbsp;</strong>of extra spaces at the beginning or at the end of each word</p>',
                'subtype' => 2,
                'image_name' => null,
                'video_name' => null,
                'extra_info' => null,
                'attempts_number' => null,
                'deleted_at' => null,
                'section_id' => 4012,
                'exercise_type_id' => 3,
                'position' => 5,
                'translated_instructions' => null,
            ],
            [
                'id' => 4072,
                'title' => 'Organization',
                'description' => 'Answer the following question',
                'instructions' => null,
                'subtype' => 99,
                'image_name' => null,
                'video_name' => null,
                'extra_info' => null,
                'attempts_number' => null,
                'deleted_at' => null,
                'section_id' => 4012,
                'exercise_type_id' => 4,
                'position' => 1,
                'translated_instructions' => null,
            ],
            [
                'id' => 4082,
                'title' => 'Dictation cloze',
                'description' => 'Listen and complete.',
                'instructions' => '<p>In this audio, you <strong>will hear</strong> how Sophie, the lyricist, tries to express to Cora how she feels about the song and the message she is trying to transmit.<strong> Listen</strong> to the audio extract and <strong>complete</strong> the missing words (one word per blank space).&nbsp;</p>\\r\\n<p><strong>Don\'t use</strong>&nbsp;capital letters, and&nbsp;<strong>be careful&nbsp;</strong>of extra spaces at the beginning or at the end of each word.</p>',
                'subtype' => 1,
                'image_name' => null,
                'video_name' => null,
                'extra_info' => null,
                'attempts_number' => null,
                'deleted_at' => null,
                'section_id' => 4013,
                'exercise_type_id' => 3,
                'position' => 4,
                'translated_instructions' => null,
            ],
            [
                'id' => 4063,
                'title' => 'Practice your vocabulary',
                'description' => 'In this exercise you will practice the vocabulary from the "activate vocabulary" exercise.',
                'instructions' => '<p><strong>Complete</strong> the words from the box in the correct sentences.</p>\\r\\n<p><strong>Don\'t&nbsp;</strong>use capital letters, and&nbsp;<strong>be careful&nbsp;</strong>of extra spaces at the beginning or at the end of each word.</p>',
                'subtype' => 2,
                'image_name' => null,
                'video_name' => null,
                'extra_info' => null,
                'attempts_number' => null,
                'deleted_at' => null,
                'section_id' => 4009,
                'exercise_type_id' => 3,
                'position' => 5,
                'translated_instructions' => null,
            ],
            [
                'id' => 4080,
                'title' => 'Checking understanding',
                'description' => 'Watch the video and answer the following questions.',
                'instructions' => '<p>You <strong>will watch</strong> a video from the film <em>Music and Lyrics</em>. In this scene, Alex Fletcher, a former pop star, is offered a surprising opportunity to write a song for a young pop sensation, Cora. He and his manager, Chris, meet with Cora&rsquo;s team to discuss the collaboration. <strong>Listen </strong>carefully and answer the following questions.</p>',
                'subtype' => 4,
                'image_name' => null,
                'video_name' => null,
                'extra_info' => null,
                'attempts_number' => null,
                'deleted_at' => null,
                'section_id' => 4013,
                'exercise_type_id' => 2,
                'position' => 2,
                'translated_instructions' => null,
            ],
            [
                'id' => 4071,
                'title' => 'Cooperating',
                'description' => 'Prepare to work in groups.',
                'instructions' => null,
                'subtype' => 99,
                'image_name' => null,
                'video_name' => null,
                'extra_info' => null,
                'attempts_number' => null,
                'deleted_at' => null,
                'section_id' => 4011,
                'exercise_type_id' => 4,
                'position' => null,
                'translated_instructions' => null,
            ],
            [
                'id' => 4047,
                'title' => 'Practice your vocabulary',
                'description' => 'In this exercise you will practice the vocabulary from the "activate vocabulary" exercise.',
                'instructions' => '<p><strong>Complete </strong>the words from the box in the correct sentences.</p>\\r\\n<p><strong>Don\'t use </strong>capital letters,and&nbsp;<strong>be careful&nbsp;</strong>of extra spaces at the beginning or at the end of each word.</p>',
                'subtype' => 2,
                'image_name' => null,
                'video_name' => null,
                'extra_info' => null,
                'attempts_number' => null,
                'deleted_at' => null,
                'section_id' => 4006,
                'exercise_type_id' => 3,
                'position' => 6,
                'translated_instructions' => null,
            ],
            [
                'id' => 4088,
                'title' => 'Cooperating',
                'description' => 'Work in groups of three',
                'instructions' => null,
                'subtype' => 99,
                'image_name' => null,
                'video_name' => null,
                'extra_info' => null,
                'attempts_number' => null,
                'deleted_at' => '2025-08-27 12:47:18',
                'section_id' => 4014,
                'exercise_type_id' => 4,
                'position' => null,
                'translated_instructions' => null,
            ],
            [
                'id' => 4089,
                'title' => 'blabla',
                'description' => null,
                'instructions' => '<p>blabla</p>',
                'subtype' => 1,
                'image_name' => null,
                'video_name' => null,
                'extra_info' => null,
                'attempts_number' => null,
                'deleted_at' => '2025-09-01 11:33:25',
                'section_id' => 4006,
                'exercise_type_id' => 2,
                'position' => null,
                'translated_instructions' => 'blabla',
            ],
            [
                'id' => 4090,
                'title' => 'Predicting',
                'description' => 'Think about what you think is going to happen in the scene you are going to watch.',
                'instructions' => null,
                'subtype' => 1,
                'image_name' => 'Captura de pantalla 2025-08-18 135610.png',
                'video_name' => null,
                'extra_info' => null,
                'attempts_number' => null,
                'deleted_at' => '2025-09-01 11:33:34',
                'section_id' => 4006,
                'exercise_type_id' => 2,
                'position' => null,
                'translated_instructions' => null,
            ],
            [
                'id' => 4085,
                'title' => 'Personal response',
                'description' => null,
                'instructions' => '<p dir="ltr"><strong>Imagine </strong>you are the manager of a singer who was famous a long time ago. Now, you want to help him become popular again. But there is a problem: the artist doesn&rsquo;t want to work hard or make much effort. <strong>How would you convince him to keep going?</strong>&nbsp;</p>\\r\\n<p dir="ltr">In the box below, write your answers explaining thoroughly the reasons behind it.</p>\\r\\n<ul>\\r\\n<li dir="ltr" aria-level="1">\\r\\n<p dir="ltr" role="presentation">I think&hellip;</p>\\r\\n</li>\\r\\n<li dir="ltr" aria-level="1">\\r\\n<p dir="ltr" role="presentation">I believe&hellip;</p>\\r\\n</li>\\r\\n<li dir="ltr" aria-level="1">\\r\\n<p dir="ltr" role="presentation">In my experience&hellip;</p>\\r\\n</li>\\r\\n<li dir="ltr" aria-level="1">\\r\\n<p dir="ltr" role="presentation">In my opinion&hellip;</p>\\r\\n</li>\\r\\n</ul>\\r\\n<p>&nbsp;</p>',
                'subtype' => 1,
                'image_name' => null,
                'video_name' => null,
                'extra_info' => null,
                'attempts_number' => null,
                'deleted_at' => null,
                'section_id' => 4014,
                'exercise_type_id' => 4,
                'position' => 2,
                'translated_instructions' => null,
            ],
            [
                'id' => 4101,
                'title' => 'Practice your vocabulary',
                'description' => 'In this exercise you will practice the vocabulary from the "activate vocabulary" exercise.',
                'instructions' => '<p><strong>Complete&nbsp;</strong>the words from the box in the correct sentences.&nbsp;<strong>Don\'t use</strong>&nbsp;capital letters, and&nbsp;<strong>be careful&nbsp;</strong>of extra spaces at the beginning or at the end of each word.</p>',
                'subtype' => 2,
                'image_name' => null,
                'video_name' => null,
                'extra_info' => null,
                'attempts_number' => null,
                'deleted_at' => null,
                'section_id' => 4015,
                'exercise_type_id' => 3,
                'position' => 5,
                'translated_instructions' => null,
            ],
            [
                'id' => 4092,
                'title' => 'Summarize',
                'description' => 'Prepare to listen.',
                'instructions' => null,
                'subtype' => 99,
                'image_name' => null,
                'video_name' => null,
                'extra_info' => null,
                'attempts_number' => null,
                'deleted_at' => null,
                'section_id' => 4016,
                'exercise_type_id' => 4,
                'position' => null,
                'translated_instructions' => null,
            ],
            [
                'id' => 4108,
                'title' => 'Personal response',
                'description' => 'Think about the characters from the scene you watched.',
                'instructions' => null,
                'subtype' => 1,
                'image_name' => null,
                'video_name' => null,
                'extra_info' => null,
                'attempts_number' => null,
                'deleted_at' => null,
                'section_id' => 4017,
                'exercise_type_id' => 4,
                'position' => 2,
                'translated_instructions' => null,
            ],
            [
                'id' => 4098,
                'title' => 'Cooperating',
                'description' => 'Prepare to work in groups',
                'instructions' => null,
                'subtype' => 99,
                'image_name' => null,
                'video_name' => null,
                'extra_info' => null,
                'attempts_number' => null,
                'deleted_at' => null,
                'section_id' => 4014,
                'exercise_type_id' => 4,
                'position' => 5,
                'translated_instructions' => null,
            ],
            [
                'id' => 4096,
                'title' => 'Predicting',
                'description' => 'Think about what you think is going to happen in the scene you are going to watch.',
                'instructions' => '<p>The pictures summarize the video.</p>',
                'subtype' => 1,
                'image_name' => 'Collage.png',
                'video_name' => null,
                'extra_info' => null,
                'attempts_number' => null,
                'deleted_at' => null,
                'section_id' => 4009,
                'exercise_type_id' => 2,
                'position' => 3,
                'translated_instructions' => null,
            ],
            [
                'id' => 4084,
                'title' => 'What do you think?',
                'description' => 'Answer the following questions',
                'instructions' => '<p><strong>Read</strong> the questions and <strong>answer</strong>. <strong>Remember</strong>, there are no correct or incorrect answers.&nbsp;</p>',
                'subtype' => 4,
                'image_name' => null,
                'video_name' => null,
                'extra_info' => null,
                'attempts_number' => null,
                'deleted_at' => null,
                'section_id' => 4014,
                'exercise_type_id' => 2,
                'position' => 1,
                'translated_instructions' => null,
            ],
            [
                'id' => 4111,
                'title' => 'Evaluate strategy',
                'description' => 'Think about the strategies/steps you used as you worked on this unit.',
                'instructions' => '<p><strong>Answer</strong> the questions below. <strong>Save your answers</strong> (digitally) to discuss them later.</p>',
                'subtype' => 99,
                'image_name' => null,
                'video_name' => null,
                'extra_info' => null,
                'attempts_number' => null,
                'deleted_at' => null,
                'section_id' => 4017,
                'exercise_type_id' => 4,
                'position' => 4,
                'translated_instructions' => null,
            ],
            [
                'id' => 4095,
                'title' => 'Predicting',
                'description' => 'Think about what you think is going to happen in the scene you are going to watch.',
                'instructions' => null,
                'subtype' => 1,
                'image_name' => 'Predicting.png',
                'video_name' => null,
                'extra_info' => null,
                'attempts_number' => null,
                'deleted_at' => '2025-09-10 10:05:19',
                'section_id' => 4006,
                'exercise_type_id' => 2,
                'position' => 4,
                'translated_instructions' => null,
            ],
            [
                'id' => 4097,
                'title' => 'Predicting',
                'description' => 'Think about what you think is going to happen in the scene you are going to watch.',
                'instructions' => '<p>Think about what you think is going to happen in the scene you are going to watch.</p>',
                'subtype' => 1,
                'image_name' => 'La la land_collage.png',
                'video_name' => null,
                'extra_info' => null,
                'attempts_number' => null,
                'deleted_at' => null,
                'section_id' => 4006,
                'exercise_type_id' => 2,
                'position' => 4,
                'translated_instructions' => null,
            ],
            [
                'id' => 4083,
                'title' => 'Organization',
                'description' => null,
                'instructions' => null,
                'subtype' => 99,
                'image_name' => null,
                'video_name' => null,
                'extra_info' => null,
                'attempts_number' => null,
                'deleted_at' => null,
                'section_id' => 4013,
                'exercise_type_id' => 6,
                'position' => 5,
                'translated_instructions' => null,
            ],
            [
                'id' => 4079,
                'title' => 'Summarizing',
                'description' => 'Prepare yourself to listen.',
                'instructions' => '<p><strong>Take</strong> notes online or on a piece of paper and <strong>write down</strong> KEY information from the listening text.&nbsp;</p>\\r\\n<p>1. <strong>Write </strong>a short summary (5&ndash;6 sentences) that explains the main ideas clearly.</p>\\r\\n<p>2. <strong>Include </strong>important supporting details or examples.</p>\\r\\n<p dir="ltr" role="presentation">3. <strong>Use </strong>linking words (e.g., however, for example, finally) to connect ideas.</p>',
                'subtype' => 99,
                'image_name' => null,
                'video_name' => null,
                'extra_info' => null,
                'attempts_number' => null,
                'deleted_at' => null,
                'section_id' => 4013,
                'exercise_type_id' => 4,
                'position' => 1,
                'translated_instructions' => null,
            ],
            [
                'id' => 4086,
                'title' => 'Personal elaboration',
                'description' => 'Answer the following question',
                'instructions' => '<p dir="ltr">What have you learned about music that can be transferred to a life-long lesson?</p>\\r\\n<ul>\\r\\n<li dir="ltr" aria-level="1">\\r\\n<p dir="ltr" role="presentation"><strong>Think </strong>about the characters&rsquo; skills, attitudes, or values shown in the videos.</p>\\r\\n</li>\\r\\n<li dir="ltr" aria-level="1">\\r\\n<p dir="ltr" role="presentation">Then, <strong>explain </strong>how these can help you in everyday life, school, or your future goals.</p>\\r\\n</li>\\r\\n</ul>\\r\\n<p dir="ltr"><strong>Example:</strong> Play hard, be tough! taught me discipline. Practicing every day showed me that small efforts lead to big results&mdash;this helps me in school and personal goals.</p>\\r\\n<p>&nbsp;</p>',
                'subtype' => 99,
                'image_name' => null,
                'video_name' => null,
                'extra_info' => null,
                'attempts_number' => null,
                'deleted_at' => null,
                'section_id' => 4014,
                'exercise_type_id' => 4,
                'position' => 3,
                'translated_instructions' => null,
            ],
            [
                'id' => 4094,
                'title' => 'Meet the characters!',
                'description' => 'Listen to Andrew and Mr. Fletcher.',
                'instructions' => '<p><strong>Listen</strong> to the main characters and <strong>familiarize</strong> <strong>yourself</strong> with their voices. Do you understand what they are saying?</p>',
                'subtype' => 1,
                'image_name' => null,
                'video_name' => null,
                'extra_info' => null,
                'attempts_number' => null,
                'deleted_at' => null,
                'section_id' => 4015,
                'exercise_type_id' => 5,
                'position' => 2,
                'translated_instructions' => null,
            ],
            [
                'id' => 4091,
                'title' => 'Organization',
                'description' => 'Think about your goal.',
                'instructions' => null,
                'subtype' => 99,
                'image_name' => null,
                'video_name' => null,
                'extra_info' => null,
                'attempts_number' => null,
                'deleted_at' => null,
                'section_id' => 4015,
                'exercise_type_id' => 4,
                'position' => 1,
                'translated_instructions' => null,
            ],
            [
                'id' => 4102,
                'title' => 'Organization',
                'description' => 'Think about listening strategies.',
                'instructions' => null,
                'subtype' => 99,
                'image_name' => null,
                'video_name' => null,
                'extra_info' => null,
                'attempts_number' => null,
                'deleted_at' => null,
                'section_id' => 4015,
                'exercise_type_id' => 6,
                'position' => 6,
                'translated_instructions' => null,
            ],
            [
                'id' => 4099,
                'title' => 'Predicting',
                'description' => 'Think about what you are going to watch.',
                'instructions' => '<p><strong>Read</strong> each statement carefully. Do you agree or disagree?</p>',
                'subtype' => 1,
                'image_name' => null,
                'video_name' => null,
                'extra_info' => null,
                'attempts_number' => null,
                'deleted_at' => null,
                'section_id' => 4015,
                'exercise_type_id' => 2,
                'position' => 3,
                'translated_instructions' => null,
            ],
            [
                'id' => 4100,
                'title' => 'Activate vocabulary',
                'description' => 'Familiarize yourself with new vocabulary.',
                'instructions' => '<p><strong>Match</strong>&nbsp;the words with their correct definitions.&nbsp;<strong>Check&nbsp;</strong>the&nbsp;<strong>glossary</strong>&nbsp;<strong>to see</strong> an example sentence for each word.</p>',
                'subtype' => 1,
                'image_name' => null,
                'video_name' => null,
                'extra_info' => null,
                'attempts_number' => null,
                'deleted_at' => null,
                'section_id' => 4015,
                'exercise_type_id' => 1,
                'position' => 4,
                'translated_instructions' => null,
            ],
            [
                'id' => 4103,
                'title' => 'Checking understanding',
                'description' => null,
                'instructions' => '<p><strong>Watch</strong>&nbsp;the video and&nbsp;<strong>answer</strong> the following questions:</p>',
                'subtype' => 4,
                'image_name' => null,
                'video_name' => null,
                'extra_info' => null,
                'attempts_number' => null,
                'deleted_at' => null,
                'section_id' => 4016,
                'exercise_type_id' => 2,
                'position' => null,
                'translated_instructions' => null,
            ],
            [
                'id' => 4104,
                'title' => 'Monitoring',
                'description' => 'Think about the challenges you faced during this listening activity.',
                'instructions' => null,
                'subtype' => 991,
                'image_name' => null,
                'video_name' => null,
                'extra_info' => null,
                'attempts_number' => null,
                'deleted_at' => null,
                'section_id' => 4016,
                'exercise_type_id' => 4,
                'position' => null,
                'translated_instructions' => null,
            ],
            [
                'id' => 4105,
                'title' => 'Dictation cloze',
                'description' => 'Listen and complete.',
                'instructions' => '<p>In this audio, you&nbsp;<strong>will hear</strong>&nbsp;how Sophie, the lyricist, tries to express to Cora how she feels about the song and the message she is trying to transmit.<strong>&nbsp;Listen</strong>&nbsp;to the audio extract and&nbsp;<strong>complete</strong>&nbsp;the missing words (one word per blank space).&nbsp;</p>\\r\\n<p><strong>Don\'t use</strong>&nbsp;capital letters, and&nbsp;<strong>be careful&nbsp;</strong>of extra spaces at the beginning or at the end of each word.</p>',
                'subtype' => 1,
                'image_name' => null,
                'video_name' => null,
                'extra_info' => null,
                'attempts_number' => null,
                'deleted_at' => null,
                'section_id' => 4016,
                'exercise_type_id' => 3,
                'position' => null,
                'translated_instructions' => null,
            ],
            [
                'id' => 4106,
                'title' => 'Organization',
                'description' => null,
                'instructions' => null,
                'subtype' => 99,
                'image_name' => null,
                'video_name' => null,
                'extra_info' => null,
                'attempts_number' => null,
                'deleted_at' => '2025-10-01 10:09:04',
                'section_id' => 4016,
                'exercise_type_id' => 6,
                'position' => null,
                'translated_instructions' => null,
            ],
            [
                'id' => 4107,
                'title' => 'Organization',
                'description' => null,
                'instructions' => null,
                'subtype' => 99,
                'image_name' => null,
                'video_name' => null,
                'extra_info' => null,
                'attempts_number' => null,
                'deleted_at' => null,
                'section_id' => 4016,
                'exercise_type_id' => 6,
                'position' => null,
                'translated_instructions' => null,
            ],
            [
                'id' => 4110,
                'title' => 'Personal elaboration',
                'description' => 'Think about what you learned during this lesson.',
                'instructions' => null,
                'subtype' => 99,
                'image_name' => null,
                'video_name' => null,
                'extra_info' => null,
                'attempts_number' => null,
                'deleted_at' => null,
                'section_id' => 4017,
                'exercise_type_id' => 4,
                'position' => 3,
                'translated_instructions' => null,
            ],
            [
                'id' => 4109,
                'title' => 'Personal elaboration',
                'description' => 'Think about what you learned during this lesson.',
                'instructions' => null,
                'subtype' => 99,
                'image_name' => null,
                'video_name' => null,
                'extra_info' => null,
                'attempts_number' => null,
                'deleted_at' => '2025-10-01 10:23:05',
                'section_id' => 4017,
                'exercise_type_id' => 6,
                'position' => null,
                'translated_instructions' => null,
            ],
            [
                'id' => 4093,
                'title' => 'What do you think?',
                'description' => 'Think about the message behind what Mr. Feltcher is saying.',
                'instructions' => '<p><strong>Read</strong> the questions and <strong>answer</strong>. Remember there are <span style="text-decoration: underline;">no</span> correct or incorrect answers.</p>',
                'subtype' => 4,
                'image_name' => null,
                'video_name' => null,
                'extra_info' => null,
                'attempts_number' => null,
                'deleted_at' => null,
                'section_id' => 4017,
                'exercise_type_id' => 2,
                'position' => 1,
                'translated_instructions' => null,
            ],
            [
                'id' => 4087,
                'title' => 'Evaluate strategy',
                'description' => 'Answer the following questions',
                'instructions' => '<p><strong>Think</strong> about the strategies/steps you used as you worked on this unit. <strong>Answer</strong> the questions below. <strong>Save </strong>your answers (digitally) to discuss them later.</p>',
                'subtype' => 99,
                'image_name' => null,
                'video_name' => null,
                'extra_info' => null,
                'attempts_number' => null,
                'deleted_at' => '2025-10-01 10:37:18',
                'section_id' => 4014,
                'exercise_type_id' => 4,
                'position' => 4,
                'translated_instructions' => null,
            ],
            [
                'id' => 4114,
                'title' => 'Evaluate strategy',
                'description' => 'Think about the strategies/steps you used as you worked on this unit.',
                'instructions' => '<p>Answer the questions below. Save your answers (digitally) to discuss them later.</p>',
                'subtype' => 99,
                'image_name' => null,
                'video_name' => null,
                'extra_info' => null,
                'attempts_number' => null,
                'deleted_at' => null,
                'section_id' => 4014,
                'exercise_type_id' => 4,
                'position' => 4,
                'translated_instructions' => null,
            ]
        ]);
    }
}
