<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use DB;

class GlossedWordSeeder extends Seeder
{
    public function run()
    {
        DB::table('glossed_words')->truncate();
        DB::table('glossed_words')->insert([
            [
                'id' => 4000,
                'word' => 'stealth',
                'description' => 'e.g. His stealth marketing campaign relied on influencers subtly featuring the track without mentioning it directly.',
                'unit_id' => 4000,
                'deleted_at' => null,
            ],
            [
                'id' => 4001,
                'word' => 'stiff',
                'description' => 'e.g. The new guitarist seemed stiff during rehearsals, probably because it was her first time playing with a professional band.',
                'unit_id' => 4000,
                'deleted_at' => null,
            ],
            [
                'id' => 4002,
                'word' => 'amp it up',
                'description' => 'to make something stronger, more extreme, or more exciting.',
                'unit_id' => 4000,
                'deleted_at' => null,
            ],
            [
                'id' => 4003,
                'word' => 'crowd',
                'description' => 'e.g. The singer paused to thank the crowd for their support, clearly moved by their enthusiastic response.',
                'unit_id' => 4000,
                'deleted_at' => null,
            ],
            [
                'id' => 4004,
                'word' => 'caveman',
                'description' => 'someone who lived in a cave in the early stages of the development of human society.',
                'unit_id' => 4000,
                'deleted_at' => null,
            ],
            [
                'id' => 4006,
                'word' => 'rhythm',
                'description' => 'a strong pattern of sounds, words, or musical notes that is used in music, poetry, and dancing.',
                'unit_id' => 4000,
                'deleted_at' => null,
            ],
            [
                'id' => 4007,
                'word' => 'cursory',
                'description' => 'quick and probably not detailed.',
                'unit_id' => 4000,
                'deleted_at' => null,
            ],
            [
                'id' => 4008,
                'word' => 'broad strokes',
                'description' => 'a general outline or simplified version of something.',
                'unit_id' => 4000,
                'deleted_at' => null,
            ],
            [
                'id' => 4009,
                'word' => 'go for it',
                'description' => 'to do anything you have to in order to get something.',
                'unit_id' => 4000,
                'deleted_at' => null,
            ],
            [
                'id' => 4010,
                'word' => 'zero in',
                'description' => 'e.g. While writing the song, they zeroed in on the theme of resilience, crafting lyrics that resonated deeply with listeners.',
                'unit_id' => 4000,
                'deleted_at' => null,
            ],
            [
                'id' => 4011,
                'word' => 'start them off',
                'description' => 'to help a person begin an activity by giving initial guidance, support, or resources.',
                'unit_id' => 4000,
                'deleted_at' => null,
            ],
            [
                'id' => 4013,
                'word' => 'locked onto something',
                'description' => 'to focus your attention on a specific element and align your actions with it.',
                'unit_id' => 4000,
                'deleted_at' => null,
            ],
            [
                'id' => 4012,
                'word' => 'ends up',
                'description' => 'to reach a particular place or achieve a situation after other activities.',
                'unit_id' => 4000,
                'deleted_at' => null,
            ],
            [
                'id' => 4014,
                'word' => 'synergizes',
                'description' => 'e.g. The band\'s strength lies in how each section synergizes with the others, creating a rich and balanced sound.',
                'unit_id' => 4000,
                'deleted_at' => null,
            ],
            [
                'id' => 4015,
                'word' => 'entire',
                'description' => 'e.g. The artist gained international fame after his entire album was featured in a popular Netflix series.',
                'unit_id' => 4000,
                'deleted_at' => null,
            ],
            [
                'id' => 4016,
                'word' => 'alive',
                'description' => 'e.g. Music keeps the memory of old times alive.',
                'unit_id' => 4001,
                'deleted_at' => null,
            ],
            [
                'id' => 4017,
                'word' => 'chords',
                'description' => 'e.g. Some jazz musicians experiment with unusual chord structures.',
                'unit_id' => 4001,
                'deleted_at' => null,
            ],
            [
                'id' => 4018,
                'word' => 'harmonics',
                'description' => 'relate to sound quality and resonance.',
                'unit_id' => 4001,
                'deleted_at' => null,
            ],
            [
                'id' => 4019,
                'word' => 'mirror',
                'description' => 'a surface, typically of glass, which reflects a clear image.',
                'unit_id' => 4001,
                'deleted_at' => null,
            ],
            [
                'id' => 4020,
                'word' => 'mouthpiece',
                'description' => 'He carefully placed the mouthpiece on his trumpet before starting to play.',
                'unit_id' => 4001,
                'deleted_at' => null,
            ],
            [
                'id' => 4021,
                'word' => 'moving people',
                'description' => 'to affect people emotionally.',
                'unit_id' => 4001,
                'deleted_at' => null,
            ],
            [
                'id' => 4022,
                'word' => 'reminds',
                'description' => 'to make someone think of something or someone else.',
                'unit_id' => 4001,
                'deleted_at' => null,
            ],
            [
                'id' => 4023,
                'word' => 'stuff',
                'description' => 'e.g. Do you have your music stuff with you — like your guitar and cables?',
                'unit_id' => 4001,
                'deleted_at' => null,
            ],
            [
                'id' => 4024,
                'word' => 'trust yourself',
                'description' => 'If you want to succeed, you have to trust yourself and your decisions.',
                'unit_id' => 4001,
                'deleted_at' => null,
            ],
            [
                'id' => 4025,
                'word' => 'cocktail party',
                'description' => 'a formal party with alcoholic drinks, usually in the early evening.',
                'unit_id' => 4002,
                'deleted_at' => null,
            ],
            [
                'id' => 4026,
                'word' => 'flop house',
                'description' => 'a very cheap, run-down place where people can sleep for the night, often with poor living conditions. Usually used by people with little or no money.',
                'unit_id' => 4002,
                'deleted_at' => null,
            ],
            [
                'id' => 4027,
                'word' => 'Kenny Clarke',
                'description' => 'Kenny "Klook" Clarke was a foundational architect of modern jazz drumming, moving the beat to the ride cymbal and adding dynamic, improvisational accents.',
                'unit_id' => 4002,
                'deleted_at' => null,
            ],
            [
                'id' => 4028,
                'word' => 'Kenny G',
                'description' => 'is an American smooth jazz saxophonist, composer, and record producer. He is one of the best-selling artists of all time, with global sales totaling more than 75 million records, making him also the best-selling instrumentalist in history.',
                'unit_id' => 4002,
                'deleted_at' => null,
            ],
            [
                'id' => 4029,
                'word' => 'Sidney Bechet',
                'description' => 'a pioneering American jazz musician, best known for his powerful and expressive playing on the soprano saxophone and clarinet. He was one of the first important soloists in jazz history, emerging at the same time as Louis Armstrong.',
                'unit_id' => 4002,
                'deleted_at' => null,
            ],
            [
                'id' => 4030,
                'word' => 'Thelonious Monk',
                'description' => 'Thelonious Monk was a pioneering American jazz pianist and composer who helped shape bebop, a fast-paced, improvisation-heavy style that broke from traditional swing. His music is known for its dissonant harmonies, rhythmic complexity, and iconic compositions like "Round Midnight."',
                'unit_id' => 4002,
                'deleted_at' => null,
            ],
            [
                'id' => 4031,
                'word' => 'at stake',
                'description' => 'e.g. With millions of dollars at stake, the team worked late into the night to finalize their proposal.',
                'unit_id' => 4002,
                'deleted_at' => null,
            ],
            [
                'id' => 4033,
                'word' => 'crammed',
                'description' => 'very full of people or things.',
                'unit_id' => 4002,
                'deleted_at' => null,
            ],
            [
                'id' => 4034,
                'word' => 'compromise',
                'description' => 'e.g. After hours of negotiation, both sides agreed to a compromise that satisfied neither completely but moved the deal forward.',
                'unit_id' => 4002,
                'deleted_at' => null,
            ],
            [
                'id' => 4035,
                'word' => 'get it out of the way',
                'description' => 'e.g. Let's get this paperwork out of the way to enjoy the rest of our afternoon.',
                'unit_id' => 4002,
                'deleted_at' => null,
            ],
            [
                'id' => 4047,
                'word' => 'notes on a page',
                'description' => 'The notes on the page were written perfectly.',
                'unit_id' => 4001,
                'deleted_at' => null,
            ],
            [
                'id' => 4037,
                'word' => 'hijack',
                'description' => 'e.g. Cyber attackers can hijack your Wi"æFi connection to intercept personal data without your knowledge.',
                'unit_id' => 4002,
                'deleted_at' => null,
            ],
            [
                'id' => 4036,
                'word' => 'had its time',
                'description' => 'e.g. Vinyl records had their time in the spotlight, but now most people stream music digitally.',
                'unit_id' => 4002,
                'deleted_at' => null,
            ],
            [
                'id' => 4038,
                'word' => 'means',
                'description' => 'to intend.',
                'unit_id' => 4002,
                'deleted_at' => null,
            ],
            [
                'id' => 4039,
                'word' => 'on my watch',
                'description' => 'e.g. Never before had a safety violation occurred on her watch, so she took the recent accident very personally.',
                'unit_id' => 4002,
                'deleted_at' => null,
            ],
            [
                'id' => 4040,
                'word' => 'premise',
                'description' => 'e.g. The novel's premise that dreams can alter reality captivated readers from the first page.',
                'unit_id' => 4002,
                'deleted_at' => null,
            ],
            [
                'id' => 4041,
                'word' => 'rearraging',
                'description' => 'e.g. She decided to rearrange her furniture to create a more open and inviting living space.',
                'unit_id' => 4002,
                'deleted_at' => null,
            ],
            [
                'id' => 4043,
                'word' => 'clarinet',
                'description' => 'She plays the clarinet in the school band every Friday.',
                'unit_id' => 4001,
                'deleted_at' => null,
            ],
            [
                'id' => 4048,
                'word' => 'sunset',
                'description' => 'We sat on the beach and watched the sunset—it was orange, pink, and beautiful.',
                'unit_id' => 4001,
                'deleted_at' => null,
            ],
            [
                'id' => 4044,
                'word' => 'giving up',
                'description' => 'She didn't win the race, but she's not giving up.',
                'unit_id' => 4001,
                'deleted_at' => '2025-08-18 12:33:32',
            ],
            [
                'id' => 4045,
                'word' => 'giving up',
                'description' => 'She didn't win the race, but she's not giving up.',
                'unit_id' => 4001,
                'deleted_at' => null,
            ],
            [
                'id' => 4046,
                'word' => 'goofing everybody up',
                'description' => 'Her mistake in the schedule goofed up the whole team.',
                'unit_id' => 4001,
                'deleted_at' => null,
            ],
            [
                'id' => 4049,
                'word' => 'blue ribbon',
                'description' => 'The band won a blue ribbon at the music festival for their amazing performance.',
                'unit_id' => 4001,
                'deleted_at' => null,
            ],
            [
                'id' => 4050,
                'word' => 'three chords',
                'description' => 'That band keeps playing the same three chords, but it is fun!',
                'unit_id' => 4001,
                'deleted_at' => null,
            ],
            [
                'id' => 4052,
                'word' => 'beggars can\'t be choosers',
                'description' => '(idiom) people who are in desperate need (the "beggars") cannot be selective or picky ("choosers") about what they receive.',
                'unit_id' => 4003,
                'deleted_at' => null,
            ],
            [
                'id' => 4053,
                'word' => 'record label',
                'description' => '(noun phrase) a company that produces, promotes, and sells music recordings by artists and bands.',
                'unit_id' => 4003,
                'deleted_at' => null,
            ],
            [
                'id' => 4054,
                'word' => 'Word Records',
                'description' => 'a well-known Christian music label in the U.S.',
                'unit_id' => 4003,
                'deleted_at' => null,
            ],
            [
                'id' => 4056,
                'word' => 'give it a go',
                'description' => '(idiom) e.g. She\'s been thinking about learning to sing for many years, and she\'s finally decided to give it a go.',
                'unit_id' => 4003,
                'deleted_at' => null,
            ],
            [
                'id' => 4057,
                'word' => 'maid',
                'description' => '(noun) a person (usually a woman) who cleans or works in someone's home.',
                'unit_id' => 4003,
                'deleted_at' => null,
            ],
            [
                'id' => 4032,
                'word' => 'blank statement',
                'description' => 'a broad generalization that may not be accurate or fair to all members of a group.',
                'unit_id' => 4002,
                'deleted_at' => null,
            ],
            [
                'id' => 4051,
                'word' => 'beggars',
                'description' => '(noun) e.g. In my city, jobs are hard to find, and many end up as street beggars.',
                'unit_id' => 4003,
                'deleted_at' => null,
            ],
            [
                'id' => 4059,
                'word' => 'face facts',
                'description' => '(idiom) e.g. you have to face facts; your business isn\'t making enough money, and changes need to be made',
                'unit_id' => 4003,
                'deleted_at' => null,
            ],
            [
                'id' => 4055,
                'word' => 'the right fit',
                'description' => '(phrase) e.g. We\'re looking for a candidate who is the right fit for our team culture and expectations.',
                'unit_id' => 4003,
                'deleted_at' => null,
            ],
            [
                'id' => 4058,
                'word' => 'being too hard on',
                'description' => '(phrase) e.g. a good manager knows exactly when to be hard on players and when to go easy on them.',
                'unit_id' => 4003,
                'deleted_at' => null,
            ],
            [
                'id' => 4061,
                'word' => 'scrubbed',
                'description' => '(verb) to clean something by rubbing hard.',
                'unit_id' => 4003,
                'deleted_at' => null,
            ],
            [
                'id' => 4060,
                'word' => 'failure',
                'description' => '(noun) the fact of not achieving what you wanted to do or were expected to do.',
                'unit_id' => 4003,
                'deleted_at' => null,
            ],
            [
                'id' => 4062,
                'word' => 'bend the knee',
                'description' => '(idiom) e.g. He would rather struggle in silence than bend the knee for help, too proud to admit he needed anyone\'s assistance.',
                'unit_id' => 4003,
                'deleted_at' => null,
            ],
            [
                'id' => 4063,
                'word' => 'record deal',
                'description' => '(noun phrase) a contract to make and sell music with a company.',
                'unit_id' => 4003,
                'deleted_at' => null,
            ],
            [
                'id' => 4065,
                'word' => 'crush',
                'description' => '(verb) to completely destroy someone's hopes, ambitions, or plans, usually in a harsh or devastating way.',
                'unit_id' => 4003,
                'deleted_at' => null,
            ],
            [
                'id' => 4066,
                'word' => 'dashed',
                'description' => '(verb) to break or destroy something suddenly (used figuratively); ruined or crushed (especially hopes or plans).',
                'unit_id' => 4003,
                'deleted_at' => null,
            ],
            [
                'id' => 4067,
                'word' => 'enough',
                'description' => '(pronoun) e.g. There are 25 textbooks per class. That should be enough for all the students.',
                'unit_id' => 4003,
                'deleted_at' => null,
            ],
            [
                'id' => 4064,
                'word' => 'crush',
                'description' => '(verb',
                'unit_id' => 4003,
                'deleted_at' => '2025-08-20 00:09:46',
            ],
            [
                'id' => 4068,
                'word' => 'audition',
                'description' => '(noun )a short performance to show your talent, usually to try to get a role in a movie, play, or music group.',
                'unit_id' => 4003,
                'deleted_at' => null,
            ],
            [
                'id' => 4069,
                'word' => 'begging',
                'description' => '(verb) Asking someone strongly and emotionally for something, especially when you are desperate.',
                'unit_id' => 4003,
                'deleted_at' => null,
            ],
            [
                'id' => 4070,
                'word' => 'business',
                'description' => '(noun) the activity of buying and selling goods and services.',
                'unit_id' => 4003,
                'deleted_at' => null,
            ],
            [
                'id' => 4071,
                'word' => 'degrading',
                'description' => '(verb)  making someone feel ashamed, embarrassed, or without value.',
                'unit_id' => 4003,
                'deleted_at' => null,
            ],
            [
                'id' => 4072,
                'word' => 'pride',
                'description' => '(noun) a feeling of pleasure and satisfaction because you or someone you know has done something good.',
                'unit_id' => 4003,
                'deleted_at' => null,
            ],
            [
                'id' => 4077,
                'word' => 'recorded',
                'description' => '(verb) To store sounds or moving pictures using electronic equipment so that they can be heard or seen later.  e.g. This band recorded their first album in 2005.',
                'unit_id' => 4004,
                'deleted_at' => null,
            ],
            [
                'id' => 4092,
                'word' => 'Apologize',
                'description' => '(verb) e.g. She apologized sincerely after realizing her comment had offended someone.',
                'unit_id' => 4005,
                'deleted_at' => null,
            ],
            [
                'id' => 4093,
                'word' => 'Decapitates',
                'description' => '(verb) e.g. In the past, some kings would decapitate criminals as a form of public execution.',
                'unit_id' => 4005,
                'deleted_at' => null,
            ],
            [
                'id' => 4095,
                'word' => 'Discourage',
                'description' => '(verb) The negative reviews didn't discourage her from publishing her book.',
                'unit_id' => 4005,
                'deleted_at' => null,
            ],
            [
                'id' => 4094,
                'word' => 'Depriving',
                'description' => '(verb) e.g. Growing up in poverty can deprive children of educational opportunities.',
                'unit_id' => 4005,
                'deleted_at' => null,
            ],
            [
                'id' => 4096,
                'word' => 'Quit',
                'description' => '(verb) e.g. After years of training, he almost quit the team, but his coach convinced him to stay',
                'unit_id' => 4005,
                'deleted_at' => null,
            ],
            [
                'id' => 4098,
                'word' => 'Laughed off',
                'description' => '(verb) e.g. She laughed off the criticism and kept working hard.',
                'unit_id' => 4005,
                'deleted_at' => null,
            ],
            [
                'id' => 4099,
                'word' => 'Moron',
                'description' => '(noun) e.g. I felt like a moron when I realized I'd been using the wrong password all day.',
                'unit_id' => 4005,
                'deleted_at' => null,
            ],
            [
                'id' => 4100,
                'word' => 'Harmful',
                'description' => '(adjective) e.g. That comment was really harmful to her self-esteem.',
                'unit_id' => 4005,
                'deleted_at' => null,
            ],
            [
                'id' => 4097,
                'word' => 'Laugh at',
                'description' => '(verb) e.g. She laughed at the movie because it was so ridiculous.',
                'unit_id' => 4005,
                'deleted_at' => '2025-08-28 14:56:09',
            ],
            [
                'id' => 4076,
                'word' => 'perform',
                'description' => '(verb) To entertain people by dancing, singing, acting, or playing music. e.g. He is performing in a local band this weekend.',
                'unit_id' => 4004,
                'deleted_at' => null,
            ],
            [
                'id' => 4075,
                'word' => 'manager',
                'description' => '(noun) A person whose job is to arrange or find work for a singer or actor, etc.  e.g. The band's manager arranged all their concerts and made sure they arrived on time for every show.',
                'unit_id' => 4004,
                'deleted_at' => null,
            ],
            [
                'id' => 4078,
                'word' => 'song',
                'description' => '(noun) A usually short piece of music with words that are sung. e.g. I think this song will become a big hit next summer.',
                'unit_id' => 4004,
                'deleted_at' => null,
            ],
            [
                'id' => 4079,
                'word' => 'audience',
                'description' => '(noun) People who watch or listen to a performance. e.g. The audience clapped loudly after the concert.',
                'unit_id' => 4004,
                'deleted_at' => null,
            ],
            [
                'id' => 4080,
                'word' => 'blow it',
                'description' => '(phrase) e.g. This is your big chance—don't blow it!',
                'unit_id' => 4004,
                'deleted_at' => null,
            ],
            [
                'id' => 4081,
                'word' => 'broke up',
                'description' => '(phrasal verb) To end a romantic relationship. e.g. They decided to break up after five years together.',
                'unit_id' => 4004,
                'deleted_at' => null,
            ],
            [
                'id' => 4082,
                'word' => 'dropped us',
                'description' => '(phrasal verb) e.g. The company dropped the accountant after the scandal.',
                'unit_id' => 4004,
                'deleted_at' => null,
            ],
            [
                'id' => 4083,
                'word' => 'edgy',
                'description' => '(adjective) e.g. Her new haircut is really edgy and cool.',
                'unit_id' => 4004,
                'deleted_at' => null,
            ],
            [
                'id' => 4084,
                'word' => 'lyricist',
                'description' => '(noun) A person who writes songs. e.g. The lyricist worked closely with the composer to create a powerful ballad.',
                'unit_id' => 4004,
                'deleted_at' => null,
            ],
            [
                'id' => 4085,
                'word' => 'snag',
                'description' => '(noun) e.g. We hit a snag while planning the event.',
                'unit_id' => 4004,
                'deleted_at' => null,
            ],
            [
                'id' => 4086,
                'word' => 'tease',
                'description' => '(verb) To make fun of someone, often in a playful way. e.g. My brother likes to tease me about my singing.',
                'unit_id' => 4004,
                'deleted_at' => null,
            ],
            [
                'id' => 4087,
                'word' => 'got me through my parents' divorce',
                'description' => '(phrase) e.g. Music really got me through my exams.',
                'unit_id' => 4004,
                'deleted_at' => '2025-09-03 10:34:51',
            ],
            [
                'id' => 4088,
                'word' => 'tunes',
                'description' => '(noun) e.g. My sister can't stop humming that catchy tune from the concert.',
                'unit_id' => 4004,
                'deleted_at' => null,
            ],
            [
                'id' => 4089,
                'word' => 'uplift',
                'description' => '(noun) e.g. Her kind words gave me a real uplift.',
                'unit_id' => 4004,
                'deleted_at' => null,
            ],
            [
                'id' => 4090,
                'word' => 'wind up',
                'description' => '(phrasal verb) e.g. If you're not careful, you'll wind up late again.',
                'unit_id' => 4004,
                'deleted_at' => null,
            ],
            [
                'id' => 4091,
                'word' => 'worships',
                'description' => '(verb) e.g. Some fans worship pop stars like gods.',
                'unit_id' => 4004,
                'deleted_at' => null,
            ]
        ]);
    }
}
