<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use DB;

class SectionSeeder extends Seeder
{
    public function run()
    {
        DB::table('sections')->truncate();
        DB::table('sections')->insert([
            [
                'id' => 1,
                'name' => 'Pre Listening',
                'underscore_name' => 'pre_listening',
                'instructions' => 'Prepare for listening: In this session, you will watch a video about Steven going to the doctor for the first time. It seems that he has suffered both emotional and physical trauma. Read the instructions carefully and complete the following exercises.',
                'unit_id' => 764,
                'deleted_at' => null,
                'position' => null,
            ],
            [
                'id' => 2,
                'name' => 'While Listening',
                'underscore_name' => 'while_listening',
                'instructions' => 'Context: You will watch a video about Steven going to the doctor for the first time. It seems that he has suffered both emotional and physical trauma. Listen carefully and answer the following questions.',
                'unit_id' => 764,
                'deleted_at' => null,
                'position' => null,
            ],
            [
                'id' => 3,
                'name' => 'Post Listening',
                'underscore_name' => 'post_listening',
                'instructions' => null,
                'unit_id' => 764,
                'deleted_at' => null,
                'position' => null,
            ],
            [
                'id' => 4001,
                'name' => 'Verification stage',
                'underscore_name' => 'verification_stage',
                'instructions' => 'In this stage, you will watch a video about a DJ named Cole Carter. He is working at party and is talking to his friend. Listen carefully and complete the exercises below.',
                'unit_id' => 4000,
                'deleted_at' => null,
                'position' => 2,
            ],
            [
                'id' => 4000,
                'name' => 'Planning stage',
                'underscore_name' => 'planning_stage',
                'instructions' => 'In this stage, you will prepare yourself to watch Cole Carter talking to his friend about how he gets people in the mood for partying. Complete the following exercies.',
                'unit_id' => 4000,
                'deleted_at' => null,
                'position' => 1,
            ],
            [
                'id' => 4002,
                'name' => 'Reflection stage',
                'underscore_name' => 'reflection_stage',
                'instructions' => 'In this stage, you will reflect on Cole Carter\'s discussion about music.',
                'unit_id' => 4000,
                'deleted_at' => null,
                'position' => 3,
            ],
            [
                'id' => 4003,
                'name' => 'Planning stage',
                'underscore_name' => 'planning_stage',
                'instructions' => 'In this stage, you will prepare yourself to watch Mr. Holland talking to his student. Complete the following exercies.',
                'unit_id' => 4001,
                'deleted_at' => null,
                'position' => null,
            ],
            [
                'id' => 4004,
                'name' => 'Verification stage',
                'underscore_name' => 'verification_stage',
                'instructions' => 'In this stage, you will watch a video about Mr. Holland talking to his student about the importance of feelings in music. Listen carefully and complete the exercises below.',
                'unit_id' => 4001,
                'deleted_at' => null,
                'position' => null,
            ],
            [
                'id' => 4005,
                'name' => 'Reflection stage',
                'underscore_name' => 'reflection_stage',
                'instructions' => 'In this stage, you will reflect on Mr. Holland\'s reflection about what it takes to inspire students to learn about music',
                'unit_id' => 4001,
                'deleted_at' => null,
                'position' => null,
            ],
            [
                'id' => 4006,
                'name' => 'Planning stage',
                'underscore_name' => 'planning_stage',
                'instructions' => 'In this stage, you will prepare yourself to watch Mia and Sebastian talking about how jazz makes each of them feel. Complete the following exercises.',
                'unit_id' => 4002,
                'deleted_at' => null,
                'position' => null,
            ],
            [
                'id' => 4007,
                'name' => 'Verification stage',
                'underscore_name' => 'verification_stage',
                'instructions' => 'In this stage, you will watch a video about Mia and Sebastian talking about how jazz makes each of them feel. Listen carefully and complete the exercises below.',
                'unit_id' => 4002,
                'deleted_at' => null,
                'position' => null,
            ],
            [
                'id' => 4008,
                'name' => 'Reflection stage',
                'underscore_name' => 'reflection_stage',
                'instructions' => 'In this stage, you will reflect on Keith\'s words to Sebastian about jazz evolving.',
                'unit_id' => 4002,
                'deleted_at' => null,
                'position' => null,
            ],
            [
                'id' => 4009,
                'name' => 'Planning stage',
                'underscore_name' => 'planning_stage',
                'instructions' => 'In this stage, you will prepare yourself to watch a family discussing whether or not to ask someone for a music audition. Complete the following exercises.',
                'unit_id' => 4003,
                'deleted_at' => null,
                'position' => null,
            ],
            [
                'id' => 4010,
                'name' => 'Verification stage',
                'underscore_name' => 'verification_stage',
                'instructions' => 'In this stage, you will watch a video about a family discussion on whether or not to ask Mr. DeGarmo for a music audition. Listen carefully and complete the exercises below.',
                'unit_id' => 4003,
                'deleted_at' => null,
                'position' => null,
            ],
            [
                'id' => 4011,
                'name' => 'Reflection stage',
                'underscore_name' => 'reflection_stage',
                'instructions' => 'In this stage, you will reflect on different ideas expressed by the Smallbone\'s family.',
                'unit_id' => 4003,
                'deleted_at' => null,
                'position' => null,
            ],
            [
                'id' => 4012,
                'name' => 'Planning stage',
                'underscore_name' => 'planning_stage',
                'instructions' => 'In this stage, you will prepare yourself to watch Alex Fletcher,  who gets an unexpected opportunity to write a song for a young superstar, Cora. As Alex feels pressure from his manager and the industry, he starts thinking about making a comeback. Complete the following exercises.',
                'unit_id' => 4004,
                'deleted_at' => null,
                'position' => null,
            ],
            [
                'id' => 4013,
                'name' => 'Verification stage',
                'underscore_name' => 'verification_stage',
                'instructions' => 'In this stage, you will watch a video about  Alex Fletcher, a former pop star, who is offered a surprising opportunity to write a song for a young pop sensation, Cora. He and his manager, Chris, meet with Cora's team to discuss the collaboration.. Listen carefully and complete the exercises below.',
                'unit_id' => 4004,
                'deleted_at' => null,
                'position' => null,
            ],
            [
                'id' => 4014,
                'name' => 'Reflection stage',
                'underscore_name' => 'reflection_stage',
                'instructions' => 'In this stage, you will reflect on Alex\'s struggles with the music industry and his own career.',
                'unit_id' => 4004,
                'deleted_at' => null,
                'position' => null,
            ],
            [
                'id' => 4015,
                'name' => 'Planning stage',
                'underscore_name' => 'planning_stage',
                'instructions' => 'In this stage, you will prepare yourself to watch  a conversation between Mr. Fletcher, an orchestra conductor, and Andrew, an aspiring drummer. Complete the following exercises.',
                'unit_id' => 4005,
                'deleted_at' => null,
                'position' => null,
            ],
            [
                'id' => 4016,
                'name' => 'Verification stage',
                'underscore_name' => 'verification_stage',
                'instructions' => 'how Mr. Fletcher worked for the Shaffer Conservatory, an elite music school known for its high standards, intense training, and competitive environment.',
                'unit_id' => 4005,
                'deleted_at' => null,
                'position' => null,
            ],
            [
                'id' => 4017,
                'name' => 'Reflection stage',
                'underscore_name' => 'reflection_stage',
                'instructions' => 'In this stage, you will reflect on the conversation between Andrew and Mr. Fletcher.',
                'unit_id' => 4005,
                'deleted_at' => null,
                'position' => null,
            ]
        ]);
    }
}
